config/routes.rb
Rails.application.routes.draw do
  root to: 'home#trend'
  get 'tag-feed', to: 'home#tag_feed'

  resources :users, only: [:index, :show]

  resources :articles do
    resources :comments, only: [:create, :destroy]

    collection do
      get :drafts
    end

    member do
      post :like, controller: :likes
      delete :unlike, controller: :likes
    end
  end

  resources :tags, only: [:index, :show, :create, :destroy]

  devise_for :users, path: :devise, controllers: { registrations: 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize

  validates :title, presence: true
  validates :body, presence: true
  enumerize :status, in: [:draft, :open], default: :draft, scope: :shallow
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable
  acts_as_votable

  default_scope { includes(:user) }

  scope :top, -> { order(updated_at: :desc) }

  def self.trend(duration, limit)
    # FIXME 重い処理なのでバッチで計算させるようにすべき

    find_by_sql([<<-'SQL', duration_begin: Time.current.ago(duration), limit: limit])
      SELECT articles.*
      FROM articles
      LEFT OUTER JOIN (
        SELECT votable_id, row_number() over (ORDER BY count(*) DESC, votable_id) row_number
        FROM votes
        WHERE votable_type = 'Article'
          AND created_at >= :duration_begin
        GROUP BY votable_id
      ) vote_count
      ON articles.id = vote_count.votable_id
      ORDER BY vote_count.row_number
      LIMIT :limit
    SQL
  end

  def self.tag_feed(tag_list)
    tagged_with(tag_list, any: true)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true

  after_create -> {ArticlesMailer.with(comment: self).create_comment_email.deliver_later}

  validates :body, presence: true

  default_scope { includes(:user) }
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :nullify
  acts_as_taggable
  acts_as_voter

  def articles_tags_count
    self.articles.joins(taggings: :tag).group('tags.name').count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article_owner, only: [:edit, :update, :destroy]

  def index
    @q = Article.ransack(articles_search_params)
    @pagy, @articles = pagy(@q.result.open.top)
  end

  def drafts
    @pagy, @articles = pagy(current_user.articles.draft.top)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      # FIXME エラー時に新規作成タグが再表示されない
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path, notice: 'Article was successfully destroyed.'
  end

  private
    def set_article_owner
      @article = current_user.articles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articles_search_params
      params.fetch(:q, {}).permit(:title_or_body_cont, :tags_name_in)
    end
    def article_params
      params.require(:article).permit(:title, :body, :status, tag_list: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.article = @article

    if @comment.save
      render
    else
      render 'error'
    end
  end

  def destroy
    @comment = current_user.comments.where(article: @article).find(params[:id])
    @comment.destroy!
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Pagy::Backend

  def trend
    @pagy, @articles = pagy_array(Article.trend(1.months, 100))
  end

  def tag_feed
    if current_user
      @pagy, @articles = pagy(Article.tag_feed(current_user.tag_list).order(created_at: :desc))
    else
      redirect_to root_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def like
    current_user.likes @article
    render 'reload'
  end

  def unlike
    current_user.unlike @article
    render 'reload'
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, tag_list: [])
    end

    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, tag_list: [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    @pagy, @tags = pagy(ActsAsTaggableOn::Tag.order(taggings_count: :desc))
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @pagy, @articles = pagy(Article.tagged_with(@tag).open.top)
  end

  def create
    @tag = set_tag(params[:tag_id])
    current_user.tags << @tag unless current_user.tags.exists?(@tag.id)
    render 'reload_row'
  end

  def destroy
    @tag = set_tag(params[:id])
    current_user.tags.destroy(@tag)
    render 'reload_row'
  end

  private
    def set_tag(id)
      @tag = ActsAsTaggableOn::Tag.find(id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    gon.tags_count = @user.articles_tags_count.to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_in_required(message, &block)
    if current_user
      capture(&block)
    else
      link_to message, new_user_session_url
    end
  end

  def side_links(paths)
    tag.div class: "list-group" do
      paths.map do |path|
        active = current_page?(path[1]) ? "active" : nil
        link_to path[0], path[1],
          class: "list-group-item list-group-item-action #{active}"
      end.join.html_safe
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def likes_link_to(article)
    if current_user.voted_up_on? article
      link_to content_tag(:i, "いいね済み", class: "fa fa-check"),
                     unlike_article_path(article), method: :delete, remote: true
    else
      link_to content_tag(:i, "いいね", class: "fa fa-thumbs-up"),
                     like_article_path(article), method: :post, remote: true
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  include Pagy::Frontend
end

app/views/articles/_article.html.haml
%tr
  %td= link_to article.title, article
  %td= link_to article.user.name, article.user
  %td= render 'tags/tags_label', tags: article.tags
  %td= render 'comments/count', article: article
  %td
    = fa_icon "thumbs-up"
    = article.get_likes.size
  - if current_user == article.user
    %td
      = link_to '編集', edit_article_path(article), class: "btn btn-primary"
      = link_to '削除', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"

app/views/articles/_form.html.haml
= form_for article do |f|

  = render "shared/error_messages", resource: article do
    %p 記事の公開に失敗しました

  .field
    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"
  .field
    .form-group
      = f.collection_select :tag_list, Tag.all, :name, :name, {},
        {multiple: "multiple", class: "js-tags-select"}
  .field
    .form-group
      = f.label :body
      = f.text_area :body, class: "form-control"
  - if article.status.draft?
    .field
      .form-group
        = f.select :status, Article.status.options, {}, {class: "custom-select custom-select-lg"}
  .actions
    = f.submit '保存', class: "btn btn-primary"

app/views/articles/_index.html.haml
%table.table
  %tbody
    = render(articles) || "１件も見つかりませんでした。"

app/views/articles/_show.html.haml
%h1
  = article.title

- if current_user == article.user
  = link_to 'Edit', edit_article_path(article)

%p
  .likes-link-to
    = log_in_required "いいねするためにはログインが必要です" do
      = likes_link_to article

%p
  = render 'tags/tags_label', tags: article.tags

%p<>
  = article.user.name
  さんが
  = distance_of_time_in_words_to_now(article.created_at)
  前に作成
  (
  = distance_of_time_in_words_to_now(article.updated_at)
  前に更新
  )

.border.rounded.text-break
  = simple_format(h(article.body))

= render "comments/list", comments: article.comments.order(:created_at)

= log_in_required "コメントをするためにはログインが必要です" do
  = render "comments/form", comment: article.comments.build

app/views/articles/drafts.html.haml
= content_for(:html_title, 'ドラフト一覧')

%h1 ドラフト一覧

= render 'index', articles: @articles

= raw pagy_bootstrap_nav(@pagy)
%br

= link_to '新規記事', new_article_url

app/views/articles/edit.html.haml
= content_for(:html_title) { '記事編集' }

%h1 記事を編集

= render 'form', article: @article

= link_to 'Show', @article

app/views/articles/index.html.haml
= content_for(:html_title, '記事一覧')

%h1 記事一覧

= search_form_for @q do |f|
  .form-group
    = f.label :title_or_body_cont
    = f.search_field :title_or_body_cont, class: "form-control"

  .form-group
    -# HACK 複数検索にしたい
    -# HACK i18nで"Tag Name"を日本語化したい
    = f.label :tags_name_in
    = f.text_field :tags_name_in, class: "form-control"

  = f.submit "検索", class: "btn btn-primary"

.mt-3
  = render 'index', articles: @articles

= raw pagy_bootstrap_nav(@pagy)
%br

- if current_user
  = link_to '新規記事', new_article_url

app/views/articles/new.html.haml
= content_for(:html_title) { '記事投稿' }
%h1 記事を投稿する

= render 'form', article: @article

= link_to 'Back', articles_path

app/views/articles/show.html.haml
= content_for(:html_title) { '記事表示' }

= render 'show', article: @article

app/views/comments/_count.html.haml
= fa_icon "comment"
= article.comments.size

app/views/comments/_form.html.haml
.comment-form
  %h5 コメントを投稿する
  = form_for [comment.article, comment], remote: true do |f|
    = render 'shared/error_messages', resource: comment do
      %p コメントの投稿に失敗しました

    .field
      .form-group
        = f.text_field :body, class: "form-control", placeholder: "コメントを入力してください..."
    .actions
      = f.submit '投稿', class: "btn btn-primary"

app/views/comments/_item.html.haml
%div{class: "comment-item-#{comment.id}"}
  %p<>
    - user = comment.user
    = user.name
    さんが
    = distance_of_time_in_words_to_now(comment.created_at)
    前にコメント

    - if comment.user == current_user
      = link_to "x", [comment.article, comment], method: :delete, remote: true, data: {confirm: '削除しますか？'}, class: "badge badge-primary"

  .border.rounded.text-break
    = simple_format(h(comment.body))

app/views/comments/_list.html.haml
%h3 コメント

.comment-list
  - comments.each do |comment|
    -# render 'item' はエラーになってしまうので仕方なく
    = render 'comments/item', comment: comment

app/views/comments/create.js.erb
(function() {
  // add new comment to last
  document
    .querySelector(".comment-list")
    .insertAdjacentHTML("beforeend", "<%= j(render 'item', comment: @comment) %>");

  // reload form
  document.querySelector(".comment-form").outerHTML =
    "<%= j(render 'form', comment: @comment.article.comments.build) %>";
}());

app/views/comments/destroy.js.erb
(function() {
  document
    .querySelector(".comment-list .comment-item-" + <%= @comment.id %>)
    .remove();
}());

app/views/comments/error.js.erb
(function() {
  // reload form
  document.querySelector(".comment-form").outerHTML =
    "<%= j(render 'form', comment: @comment) %>";
}());

app/views/home/_side.html.haml
.col-3
  = side_links([["トレンド", root_path], ["タグフィード", tag_feed_path]])

app/views/home/index.html.haml
= content_for(:html_title) { 'ホーム' }

%h1 トレンド

= render 'articles/index', articles: @articles
= raw pagy_bootstrap_nav(@pagy)

app/views/home/tag_feed.html.haml
= content_for(:html_title) { 'タグフィード' }

.row
  = render "side"

  .col
    %h1 タグフィード

    = render 'articles/index', articles: @articles
    = raw pagy_bootstrap_nav(@pagy)

app/views/home/trend.html.haml
= content_for(:html_title) { 'トレンド' }

.row
  = render "side"

  .col
    %h1 トレンド

    %table.table
      %tbody
        - @articles.each do |article|
          %tr
            %td
              .row
                .col-auto= link_to article.title, article
              .row.list-secondary
                .col-auto
                  by
                  = link_to  article.user.name, article.user
                .col-auto= I18n.with_locale(:en) { distance_of_time_in_words_to_now(article.created_at) } + " ago"
                .col-auto
                  = fa_icon "thumbs-up"
                  = article.get_likes.size

    = raw pagy_bootstrap_nav(@pagy)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title= content_for?(:html_title) ? yield(:html_title) + " - QiitaClone" : "QiitaClone"
    = Gon::Base.render_data
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      %a.navbar-brand{:href => root_path} Qiita Clone
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            %a.nav-link{:href => articles_path}
              記事一覧
          %li.nav-item
            %a.nav-link{:href => users_path}
              ユーザ一覧
          %li.nav-item
            %a.nav-link{:href => tags_path}
              タグ一覧
          - if user_signed_in?
            %li.nav-item
              %a.nav-link.border.border-dark.rounded{:href => new_article_path}
                投稿する
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                マイメニュー
              .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                = link_to "自分の記事", articles_path, class: "dropdown-item"
                = link_to "ドラフトの記事", drafts_articles_path, class: "dropdown-item"
                = link_to "プロフィール", edit_user_registration_path, class: "dropdown-item"
                = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item"
          - else
            %a.nav-link{:href => new_user_session_path}
              ログイン

        = search_form_for Article.ransack, class: "form-inline my-2 my-lg-0" do |f|
          .form-group
            = f.search_field :title_or_body_cont, placeholder: "ここに入力",
              class: "form-control mr-sm-2", "aria-label" => "Search"
          = submit_tag "検索", class: "btn btn-outline-success my-2 my-sm-0"

    .container.mt-3
      - if notice.present?
        .alert.alert-primary
          %p.notice
            = notice
      - if alert.present?
        .alert.alert-danger
          %p.alert
            = alert

      = yield

app/views/likes/reload.js.erb
(function () {
  document.querySelector(".likes-link-to").innerHTML = "<%= j(likes_link_to(@article)) %>"
}());

app/views/shared/_error_messages.html.haml
- if resource.errors.any?
  .alert.alert-danger
    = yield
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/tags/_show.html.haml
- tags.each do |tag|
  = link_to tag.name, tag_path(tag), class: "badge badge-primary"

app/views/tags/_tag.html.haml
%tr{class: "tags-row-#{tag.id}"}
  %td
    = link_to tag.name, tag_path(tag)
  %td
    = fa_icon "heart"
    = tag.taggings_count
  %td
    - if current_user
      - if current_user.tags.include?(tag)
        = form_tag tag_path(tag),  method: :delete, remote: true do
          = submit_tag "フォロー解除", class: "btn btn-primary"
      - else
        = form_tag tags_path, remote: true do
          = hidden_field_tag :tag_id, tag.id
          = submit_tag "フォロー", class: "btn btn-primary"

app/views/tags/_tags_label.html.haml
- tags.each do |tag|
  = link_to tag.name, tag_path(tag), class: "badge badge-primary"

app/views/tags/index.html.haml
= content_for(:html_title) { 'タグ一覧' }

%h1 タグ一覧

%table.table.tags-table
  %tbody
    = render(partial: 'tags/tag', collection: @tags, as: :tag) || "１件も見つかりませんでした。"

= raw pagy_bootstrap_nav(@pagy)

app/views/tags/reload_row.js.erb
(function () {
  const selector = ".tags-table .tags-row-" + <%= @tag.id %>;
  const html = "<%= j(render 'tag', tag: @tag)  %>";
  document.querySelector(selector).innerHTML = html;
}());

app/views/tags/show.html.haml
%h1= @tag.name

= render 'articles/index', articles: @articles
= raw pagy_bootstrap_nav(@pagy)

app/views/users/index.html.haml
= content_for(:html_title, 'ユーザ一覧')

%h1 ユーザ一覧

%table.table
  %thead
    %tr
      %th
        名前
      %th
        メールアドレス
  %tbody
    - @users.each do |user|
      %tr
        %td
          = link_to user.name, user
        %td
          = link_to user.email, user

app/views/users/show.html.haml
%h1
  = @user.name

.js-tags-chart

%p
  = render 'tags/tags_label', tags: @user.tags

= render 'articles/index', articles: @user.articles.open